// ─────────────────────────────────────────────────────────────────
// TRANSLATIONS
// ─────────────────────────────────────────────────────────────────
const T = {
  en: {
    brand: "MONOLITH",
    tagline: "An atelier of wearable architecture",
    nav: {
      shop: "Shop",
      collections: "Collections",
      journal: "Journal",
      stores: "Stores",
      account: "Account",
      admin: "Admin",
      cart: "Bag",
      login: "Log in",
      signup: "Sign up",
      logout: "Log out",
    },
    hero: {
      season: "SS / 26 · Capsule No. 04",
      title: "FORM IS\nNOT A LUXURY",
      sub: "Twenty-three pieces, cut from a single architectural language. Drops on the 14th.",
      cta: "Enter the collection",
      ctaAlt: "Read the manifesto",
    },
    catalog: {
      title: "Catalogue",
      results: "pieces",
      sort: "Sort",
      filters: "Filters",
      category: "Category",
      size: "Size",
      color: "Colour",
      price: "Price",
      material: "Material",
      clear: "Clear all",
      apply: "Apply",
      quickView: "Quick view",
      addBag: "Add to bag",
      sold: "Sold out",
      new: "New",
      sortOptions: ["Newest", "Price ↑", "Price ↓", "Best selling"],
      categories: ["Outerwear", "Knitwear", "Trousers", "Shirts", "Tailoring", "Footwear"],
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Bone", "Ink", "Rust", "Olive", "Stone", "Navy"],
      materials: ["Wool", "Cotton", "Linen", "Leather", "Cashmere"],
    },
    qv: {
      composition: "Composition",
      fit: "Fit",
      care: "Care",
      shipping: "Shipping",
      sizeGuide: "Size guide",
      selectSize: "Select size",
      details: "Details",
    },
    auth: {
      loginTitle: "Welcome back",
      loginSub: "Your archive is waiting.",
      signupTitle: "Open an account",
      signupSub: "One ledger. All your orders, fittings and saved looks.",
      email: "Email",
      password: "Password",
      name: "Full name",
      confirm: "Confirm password",
      remember: "Keep me signed in",
      forgot: "Forgotten password",
      continue: "Continue",
      orContinue: "or continue with",
      switchToSignup: "New here? Open an account",
      switchToLogin: "Already have an account? Log in",
      agree: "I agree to the terms & privacy policy",
      passwordHint: "Min. 8 characters, one number, one symbol.",
    },
    error: {
      code: "404",
      title: "Off-pattern",
      sub: "The page you're looking for has been cut from this season's run.",
      home: "Return to storefront",
      search: "Browse the catalogue",
    },
    user: {
      hello: "Hello",
      member: "Member since",
      tabs: ["Overview", "Orders", "Profile", "Addresses", "Wishlist", "Settings"],
      overview: "Overview",
      activeOrders: "Active orders",
      totalSpend: "Lifetime spend",
      loyalty: "Atelier credit",
      recent: "Recent activity",
      orders: "Order history",
      track: "Track",
      view: "View",
      reorder: "Reorder",
      status: {
        delivered: "Delivered",
        intransit: "In transit",
        preparing: "Preparing",
        cancelled: "Cancelled",
        returned: "Returned",
      },
      profile: "Profile",
      saveChanges: "Save changes",
      wishlist: "Saved pieces",
    },
    admin: {
      title: "Operations",
      tabs: ["Dashboard", "Products", "CRM", "CMS", "Social", "Orders", "Settings"],
      kpis: {
        revenue: "Revenue (30d)",
        orders: "Orders (30d)",
        aov: "Avg. order value",
        ctr: "Storefront CTR",
        returning: "Returning rate",
        stock: "Low-stock SKUs",
      },
      sections: {
        revenue: "Revenue by channel",
        topProducts: "Top selling pieces",
        liveOrders: "Live order feed",
        traffic: "Traffic — last 7 days",
      },
      view: "View all",
    },
    crm: {
      title: "Relationship ledger",
      sub: "Suppliers, clients and the threads between them.",
      tabs: ["Clients", "Suppliers"],
      addClient: "New client",
      addSupplier: "New supplier",
      search: "Search ledger",
      columns: {
        name: "Name",
        contact: "Contact",
        location: "Location",
        status: "Status",
        value: "LTV",
        lastOrder: "Last order",
        category: "Category",
        leadTime: "Lead time",
      },
    },
    cms: {
      title: "Editorial",
      sub: "Banners, longform, policies — the voice of the house.",
      tabs: ["Banners", "Pages", "Policies", "Newsletters"],
      preview: "Preview",
      publish: "Publish",
      draft: "Draft",
      live: "Live",
      scheduled: "Scheduled",
      title2: "Headline",
      body: "Body copy",
      cta: "CTA label",
      schedule: "Publish on",
    },
    products: {
      title: "Inventory",
      sub: "Twenty-three SKUs across six categories.",
      add: "New piece",
      bulk: "Bulk edit",
      export: "Export CSV",
      columns: {
        piece: "Piece",
        sku: "SKU",
        category: "Category",
        stock: "Stock",
        price: "Price",
        status: "Status",
      },
      editing: "Editing",
      newPiece: "New piece",
      name: "Name",
      slug: "Slug",
      sku: "SKU",
      description: "Description",
      category: "Category",
      price: "Price",
      stock: "Stock by size",
      images: "Imagery",
      save: "Save piece",
      cancel: "Cancel",
      delete: "Delete",
      confirmDelete: "Delete this piece?",
      published: "Published",
      hidden: "Hidden",
    },
    settings: {
      title: "House settings",
      sub: "Defaults that apply across the storefront and back-of-house.",
      sections: {
        regional: "Regional",
        payments: "Payment rails",
        shipping: "Shipping",
        taxes: "Taxes",
        team: "Team & access",
        danger: "Danger zone",
      },
      defaultLang: "Default language",
      currency: "Display currency",
      timezone: "Timezone",
      rateCard: "Active rate card",
      paymentMethods: "Payment methods",
      enable: "Enable",
      disable: "Disable",
      enabled: "Enabled",
      disabled: "Disabled",
      saveAll: "Save settings",
    },
    social: {
      title: "Social hub",
      sub: "WhatsApp Business + Instagram, threaded into the storefront.",
      tabs: ["Overview", "Inbox", "Catalog sync", "Content studio", "Analytics"],
      kpis: {
        connected: "Accounts connected",
        unread: "Unread threads",
        scheduled: "Scheduled posts",
        attributed: "Social revenue (30d)",
        followers: "Followers (IG)",
        subscribers: "Subscribers (WA)",
      },
      channels: {
        instagram: "Instagram",
        whatsapp: "WhatsApp",
      },
      inbox: {
        all: "All",
        unread: "Unread",
        priority: "Priority",
        resolved: "Resolved",
        searchPlaceholder: "Search threads, customers…",
        reply: "Reply",
        attach: "Attach piece",
        quote: "Send quote",
        markRead: "Mark read",
        assign: "Assign",
        empty: "Pick a conversation to read.",
        typing: "typing…",
        composer: "Write a reply…",
        templates: "Templates",
      },
      sync: {
        title: "Catalog sync",
        sub: "Stock and pricing mirrored to every connected surface.",
        force: "Force sync now",
        lastSync: "Last sync",
        coverage: "Coverage",
        ok: "Synced",
        stale: "Stale",
        error: "Error",
        unlisted: "Not listed",
        igShop: "Instagram Shop",
        waCatalog: "WhatsApp Catalog",
      },
      studio: {
        title: "Content studio",
        sub: "Plan, draft and ship across surfaces from one room.",
        new: "New post",
        formats: ["Feed", "Story", "Reel", "WA broadcast"],
        schedule: "Schedule",
        publish: "Publish now",
        attach: "Attach product",
        crosspost: "Cross-post to",
      },
      analytics: {
        title: "Reach & conversion",
        reach: "Reach (30d)",
        engage: "Engagement",
        clickThru: "Click-through",
        attributed: "Attributed orders",
        top: "Top posts",
        funnel: "Funnel — last 30 days",
      },
    },
    common: {
      search: "Search",
      close: "Close",
      cancel: "Cancel",
      confirm: "Confirm",
      save: "Save",
      edit: "Edit",
      delete: "Delete",
      back: "Back",
      next: "Next",
      yes: "Yes",
      no: "No",
      all: "All",
      from: "from",
      to: "to",
      footerCopy: "Cut, sewn and shipped from Lisboa. © MMXXVI.",
    },
    checkout: {
      title: "Checkout",
      eyebrow: "Secure · 256-bit · Lisboa atelier",
      steps: ["Contact", "Shipping", "Delivery", "Payment", "Review"],
      contact: {
        title: "Who's collecting",
        sub: "We'll send order updates, fitting invitations and tracking here.",
        email: "Email address",
        phone: "Phone (for delivery)",
        guest: "I'd rather check out as a guest",
        marketing: "Send me the atelier's seasonal letter",
      },
      shipping: {
        title: "Shipping address",
        sub: "Twenty-three pieces, hand-finished in Lisboa, delivered DDP worldwide.",
        first: "First name",
        last: "Last name",
        address1: "Street, number",
        address2: "Apartment, floor (optional)",
        city: "City",
        state: "State / region",
        zip: "Postal code",
        country: "Country",
        company: "Company (optional)",
        sameBilling: "Use this address for billing",
      },
      delivery: {
        title: "Delivery method",
        sub: "Pick the speed of the house's hand.",
        options: [
          { id: "atelier", l: "Atelier delivery",       sub: "Hand-delivered in Lisboa within 24h",     price: 0,    eta: "24h" },
          { id: "express", l: "Express · DHL Sensitive", sub: "3-5 business days, DDP, signature on receipt", price: 24, eta: "3-5 d" },
          { id: "standard", l: "Standard · DPD Premium", sub: "5-8 business days, tracked, carbon-balanced", price: 0, eta: "5-8 d", note: "Free over €240" },
          { id: "pickup",  l: "Pickup at Casa MONOLITH",  sub: "Rua do Século 7, Lisboa · by appointment",  price: 0, eta: "Anytime" },
        ],
      },
      payment: {
        title: "Payment",
        sub: "We never store the full card number.",
        cardNumber: "Card number",
        cardName: "Name on card",
        cardExpiry: "Expires",
        cardCVC: "CVC",
        saveCard: "Save this card for future orders",
        billing: "Billing address",
        billSame: "Same as shipping",
        methods: ["Card", "Apple Pay", "PayPal", "Klarna"],
        terms: "By placing the order you agree to the terms of service and the privacy policy.",
        place: "Place order",
        placing: "Placing…",
      },
      review: {
        title: "One last look",
        sub: "Make sure every line is right before we cut the order.",
        editStep: "Edit",
      },
      summary: {
        title: "Order summary",
        items: "items",
        subtotal: "Subtotal",
        shipping: "Shipping",
        tax: "Tax (VAT 23%)",
        discount: "Discount",
        credit: "Atelier credit",
        total: "Total",
        promo: "Promo or atelier code",
        apply: "Apply",
        confidence: [
          "DDP worldwide — no surprises at the border",
          "30-day returns on full-price pieces",
          "Tailoring included, atelier-led",
        ],
        edit: "Edit cart",
        size: "Size",
        qty: "Qty",
      },
      success: {
        title: "Order placed",
        eyebrow: "Thank you",
        sub: "We've sent a confirmation. Your archive is being updated.",
        nextSteps: "Next steps",
        viewOrder: "View order",
        keep: "Keep shopping",
      },
    },
    order: {
      title: "Order",
      placed: "Placed on",
      arrival: "Estimated arrival",
      track: "Track package",
      invoice: "Download invoice",
      reorder: "Reorder",
      contact: "Contact the atelier",
      report: "Report an issue",
      eyebrow: "Order ledger",
      sections: {
        timeline: "Timeline",
        items: "Pieces",
        shipping: "Shipping",
        billing: "Billing & payment",
        support: "Support",
      },
      stages: {
        ordered:   "Order placed",
        cut:       "Cut",
        sewn:      "Sewn & pressed",
        packed:    "Packed in Lisboa",
        shipped:   "Shipped",
        outForDelivery: "Out for delivery",
        delivered: "Delivered",
      },
      carrier: "Carrier",
      tracking: "Tracking",
      shippingMethod: "Method",
      address: "Address",
      billed: "Billed to",
      paid: "Paid with",
      back: "All orders",
    },
  },
  es: {
    brand: "MONOLITH",
    tagline: "Un taller de arquitectura vestible",
    nav: {
      shop: "Tienda",
      collections: "Colecciones",
      journal: "Diario",
      stores: "Tiendas",
      account: "Cuenta",
      admin: "Admin",
      cart: "Bolso",
      login: "Iniciar sesión",
      signup: "Registrarse",
      logout: "Cerrar sesión",
    },
    hero: {
      season: "PV / 26 · Cápsula Nº 04",
      title: "LA FORMA\nNO ES LUJO",
      sub: "Veintitrés piezas cortadas desde un mismo lenguaje arquitectónico. Lanzamiento el día 14.",
      cta: "Entrar en la colección",
      ctaAlt: "Leer el manifiesto",
    },
    catalog: {
      title: "Catálogo",
      results: "piezas",
      sort: "Orden",
      filters: "Filtros",
      category: "Categoría",
      size: "Talla",
      color: "Color",
      price: "Precio",
      material: "Material",
      clear: "Limpiar",
      apply: "Aplicar",
      quickView: "Vista rápida",
      addBag: "Añadir al bolso",
      sold: "Agotado",
      new: "Nuevo",
      sortOptions: ["Más reciente", "Precio ↑", "Precio ↓", "Más vendido"],
      categories: ["Abrigos", "Punto", "Pantalones", "Camisas", "Sastrería", "Calzado"],
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Hueso", "Tinta", "Óxido", "Oliva", "Piedra", "Marino"],
      materials: ["Lana", "Algodón", "Lino", "Cuero", "Cachemir"],
    },
    qv: {
      composition: "Composición",
      fit: "Corte",
      care: "Cuidado",
      shipping: "Envío",
      sizeGuide: "Guía de tallas",
      selectSize: "Elegir talla",
      details: "Detalles",
    },
    auth: {
      loginTitle: "Bienvenida de nuevo",
      loginSub: "Tu archivo te está esperando.",
      signupTitle: "Abrir una cuenta",
      signupSub: "Un solo libro. Todos tus pedidos, pruebas y prendas guardadas.",
      email: "Correo electrónico",
      password: "Contraseña",
      name: "Nombre completo",
      confirm: "Confirmar contraseña",
      remember: "Mantener sesión iniciada",
      forgot: "Olvidé mi contraseña",
      continue: "Continuar",
      orContinue: "o continuar con",
      switchToSignup: "¿Eres nuevo? Abre una cuenta",
      switchToLogin: "¿Ya tienes cuenta? Inicia sesión",
      agree: "Acepto los términos y la política de privacidad",
      passwordHint: "Mín. 8 caracteres, un número, un símbolo.",
    },
    error: {
      code: "404",
      title: "Fuera de patrón",
      sub: "La página que buscas fue cortada del tiraje de esta temporada.",
      home: "Volver a la tienda",
      search: "Explorar el catálogo",
    },
    user: {
      hello: "Hola",
      member: "Miembro desde",
      tabs: ["Resumen", "Pedidos", "Perfil", "Direcciones", "Lista", "Ajustes"],
      overview: "Resumen",
      activeOrders: "Pedidos activos",
      totalSpend: "Gasto total",
      loyalty: "Crédito atelier",
      recent: "Actividad reciente",
      orders: "Historial de pedidos",
      track: "Seguir",
      view: "Ver",
      reorder: "Pedir de nuevo",
      status: {
        delivered: "Entregado",
        intransit: "En tránsito",
        preparing: "Preparando",
        cancelled: "Cancelado",
        returned: "Devuelto",
      },
      profile: "Perfil",
      saveChanges: "Guardar cambios",
      wishlist: "Piezas guardadas",
    },
    admin: {
      title: "Operaciones",
      tabs: ["Panel", "Productos", "CRM", "CMS", "Social", "Pedidos", "Ajustes"],
      kpis: {
        revenue: "Ingresos (30d)",
        orders: "Pedidos (30d)",
        aov: "Ticket medio",
        ctr: "CTR tienda",
        returning: "Tasa recurrente",
        stock: "Stock bajo",
      },
      sections: {
        revenue: "Ingresos por canal",
        topProducts: "Piezas más vendidas",
        liveOrders: "Pedidos en vivo",
        traffic: "Tráfico — últimos 7 días",
      },
      view: "Ver todo",
    },
    crm: {
      title: "Libro de relaciones",
      sub: "Proveedores, clientes y los hilos entre ellos.",
      tabs: ["Clientes", "Proveedores"],
      addClient: "Nuevo cliente",
      addSupplier: "Nuevo proveedor",
      search: "Buscar en el libro",
      columns: {
        name: "Nombre",
        contact: "Contacto",
        location: "Ubicación",
        status: "Estado",
        value: "Valor total",
        lastOrder: "Último pedido",
        category: "Categoría",
        leadTime: "Plazo",
      },
    },
    cms: {
      title: "Editorial",
      sub: "Banners, contenido y políticas — la voz de la casa.",
      tabs: ["Banners", "Páginas", "Políticas", "Newsletter"],
      preview: "Vista previa",
      publish: "Publicar",
      draft: "Borrador",
      live: "Activo",
      scheduled: "Programado",
      title2: "Titular",
      body: "Cuerpo",
      cta: "Texto del botón",
      schedule: "Publicar el",
    },
    products: {
      title: "Inventario",
      sub: "Veintitrés referencias en seis categorías.",
      add: "Nueva pieza",
      bulk: "Edición masiva",
      export: "Exportar CSV",
      columns: {
        piece: "Pieza",
        sku: "SKU",
        category: "Categoría",
        stock: "Stock",
        price: "Precio",
        status: "Estado",
      },
      editing: "Editando",
      newPiece: "Nueva pieza",
      name: "Nombre",
      slug: "Slug",
      sku: "SKU",
      description: "Descripción",
      category: "Categoría",
      price: "Precio",
      stock: "Stock por talla",
      images: "Imágenes",
      save: "Guardar pieza",
      cancel: "Cancelar",
      delete: "Eliminar",
      confirmDelete: "¿Eliminar esta pieza?",
      published: "Publicado",
      hidden: "Oculto",
    },
    settings: {
      title: "Ajustes de la casa",
      sub: "Configuración por defecto para tienda y trastienda.",
      sections: {
        regional: "Regional",
        payments: "Pasarelas",
        shipping: "Envíos",
        taxes: "Impuestos",
        team: "Equipo y accesos",
        danger: "Zona peligrosa",
      },
      defaultLang: "Idioma por defecto",
      currency: "Moneda",
      timezone: "Zona horaria",
      rateCard: "Tarifa activa",
      paymentMethods: "Métodos de pago",
      enable: "Activar",
      disable: "Desactivar",
      enabled: "Activado",
      disabled: "Desactivado",
      saveAll: "Guardar ajustes",
    },
    social: {
      title: "Centro social",
      sub: "WhatsApp Business + Instagram, hilados a la tienda.",
      tabs: ["Resumen", "Bandeja", "Sincronización", "Estudio", "Analítica"],
      kpis: {
        connected: "Cuentas conectadas",
        unread: "Sin leer",
        scheduled: "Publicaciones programadas",
        attributed: "Ingresos sociales (30d)",
        followers: "Seguidores (IG)",
        subscribers: "Suscriptores (WA)",
      },
      channels: {
        instagram: "Instagram",
        whatsapp: "WhatsApp",
      },
      inbox: {
        all: "Todo",
        unread: "Sin leer",
        priority: "Prioritarios",
        resolved: "Resueltos",
        searchPlaceholder: "Buscar conversaciones, clientes…",
        reply: "Responder",
        attach: "Adjuntar pieza",
        quote: "Enviar cotización",
        markRead: "Marcar leído",
        assign: "Asignar",
        empty: "Elige una conversación para leer.",
        typing: "escribiendo…",
        composer: "Escribe una respuesta…",
        templates: "Plantillas",
      },
      sync: {
        title: "Sincronización de catálogo",
        sub: "Stock y precio reflejados en cada superficie conectada.",
        force: "Sincronizar ahora",
        lastSync: "Última sync",
        coverage: "Cobertura",
        ok: "Sincronizado",
        stale: "Desfasado",
        error: "Error",
        unlisted: "Sin publicar",
        igShop: "Instagram Shop",
        waCatalog: "Catálogo WhatsApp",
      },
      studio: {
        title: "Estudio de contenido",
        sub: "Planifica, redacta y envía a todas las superficies desde una sola sala.",
        new: "Nueva publicación",
        formats: ["Feed", "Historia", "Reel", "Difusión WA"],
        schedule: "Programar",
        publish: "Publicar ahora",
        attach: "Adjuntar pieza",
        crosspost: "Cross-post a",
      },
      analytics: {
        title: "Alcance y conversión",
        reach: "Alcance (30d)",
        engage: "Engagement",
        clickThru: "CTR",
        attributed: "Pedidos atribuidos",
        top: "Mejor contenido",
        funnel: "Embudo — últimos 30 días",
      },
    },
    common: {
      search: "Buscar",
      close: "Cerrar",
      cancel: "Cancelar",
      confirm: "Confirmar",
      save: "Guardar",
      edit: "Editar",
      delete: "Eliminar",
      back: "Atrás",
      next: "Siguiente",
      yes: "Sí",
      no: "No",
      all: "Todo",
      from: "desde",
      to: "hasta",
      footerCopy: "Cortado, cosido y enviado desde Lisboa. © MMXXVI.",
    },
    checkout: {
      title: "Caja",
      eyebrow: "Seguro · 256-bit · Atelier Lisboa",
      steps: ["Contacto", "Envío", "Entrega", "Pago", "Revisar"],
      contact: {
        title: "Quién recibe",
        sub: "Enviaremos avisos del pedido, citas de prueba y seguimiento a este contacto.",
        email: "Correo electrónico",
        phone: "Teléfono (para la entrega)",
        guest: "Prefiero comprar como invitado",
        marketing: "Quiero recibir la carta estacional del atelier",
      },
      shipping: {
        title: "Dirección de envío",
        sub: "Veintitrés piezas, terminadas a mano en Lisboa, entregadas DDP a todo el mundo.",
        first: "Nombre",
        last: "Apellidos",
        address1: "Calle, número",
        address2: "Piso, puerta (opcional)",
        city: "Ciudad",
        state: "Provincia / región",
        zip: "Código postal",
        country: "País",
        company: "Empresa (opcional)",
        sameBilling: "Usar esta dirección también para la facturación",
      },
      delivery: {
        title: "Método de entrega",
        sub: "Elige la velocidad de la mano de la casa.",
        options: [
          { id: "atelier", l: "Entrega atelier",         sub: "Entregada en mano en Lisboa en 24 h",      price: 0,    eta: "24 h" },
          { id: "express", l: "Express · DHL Sensitive", sub: "3-5 días, DDP, firma a la recepción",      price: 24,   eta: "3-5 d" },
          { id: "standard", l: "Estándar · DPD Premium", sub: "5-8 días, con seguimiento, compensada",   price: 0,    eta: "5-8 d", note: "Gratis desde 240 €" },
          { id: "pickup",  l: "Recogida en Casa MONOLITH", sub: "Rua do Século 7, Lisboa · con cita",     price: 0,    eta: "Cuando quieras" },
        ],
      },
      payment: {
        title: "Pago",
        sub: "Nunca guardamos el número completo de la tarjeta.",
        cardNumber: "Número de tarjeta",
        cardName: "Nombre en la tarjeta",
        cardExpiry: "Vence",
        cardCVC: "CVC",
        saveCard: "Guardar esta tarjeta para próximos pedidos",
        billing: "Dirección de facturación",
        billSame: "Igual que el envío",
        methods: ["Tarjeta", "Apple Pay", "PayPal", "Klarna"],
        terms: "Al hacer el pedido aceptas los términos del servicio y la política de privacidad.",
        place: "Hacer pedido",
        placing: "Procesando…",
      },
      review: {
        title: "Una última mirada",
        sub: "Asegúrate de que cada línea es correcta antes de que cortemos el pedido.",
        editStep: "Editar",
      },
      summary: {
        title: "Resumen del pedido",
        items: "piezas",
        subtotal: "Subtotal",
        shipping: "Envío",
        tax: "IVA (23%)",
        discount: "Descuento",
        credit: "Crédito atelier",
        total: "Total",
        promo: "Código promo o atelier",
        apply: "Aplicar",
        confidence: [
          "DDP a todo el mundo — sin sorpresas en aduana",
          "30 días de devolución en precio completo",
          "Arreglos incluidos, dirigidos por el atelier",
        ],
        edit: "Editar carrito",
        size: "Talla",
        qty: "Cant.",
      },
      success: {
        title: "Pedido realizado",
        eyebrow: "Gracias",
        sub: "Te hemos enviado la confirmación. Tu archivo se está actualizando.",
        nextSteps: "Siguientes pasos",
        viewOrder: "Ver pedido",
        keep: "Seguir explorando",
      },
    },
    order: {
      title: "Pedido",
      placed: "Realizado el",
      arrival: "Llegada estimada",
      track: "Seguir paquete",
      invoice: "Descargar factura",
      reorder: "Pedir de nuevo",
      contact: "Contactar al atelier",
      report: "Reportar un problema",
      eyebrow: "Libro de pedidos",
      sections: {
        timeline: "Línea de tiempo",
        items: "Piezas",
        shipping: "Envío",
        billing: "Facturación y pago",
        support: "Soporte",
      },
      stages: {
        ordered:   "Pedido realizado",
        cut:       "Cortado",
        sewn:      "Cosido y prensado",
        packed:    "Empaquetado en Lisboa",
        shipped:   "Enviado",
        outForDelivery: "En reparto",
        delivered: "Entregado",
      },
      carrier: "Transportista",
      tracking: "Seguimiento",
      shippingMethod: "Método",
      address: "Dirección",
      billed: "Facturado a",
      paid: "Pagado con",
      back: "Todos los pedidos",
    },
  },
};

// ─────────────────────────────────────────────────────────────────
// PRODUCTS
// ─────────────────────────────────────────────────────────────────
const PRODUCTS = [
  { id: "M-01", name: { en: "Architect's Coat", es: "Abrigo del arquitecto" }, sku: "MO-AC-001", cat: "Outerwear", catEs: "Abrigos", price: 1240, stripe: "stripes-dark", colorChip: "#0a0a0a", colors: ["Ink","Stone"], sizes: ["S","M","L","XL"], material: "Wool", new: true, stock: { XS:0, S:6, M:8, L:4, XL:2 } },
  { id: "M-02", name: { en: "Pleated Trouser 04", es: "Pantalón plisado 04" }, sku: "MO-PT-004", cat: "Trousers", catEs: "Pantalones", price: 420, stripe: "stripes-sand", colorChip: "#d9cdb6", colors: ["Bone","Olive"], sizes: ["XS","S","M","L"], material: "Wool", stock: { XS:3, S:9, M:11, L:7, XL:0 } },
  { id: "M-03", name: { en: "Bone Cashmere Crew", es: "Crew cachemir hueso" }, sku: "MO-CC-007", cat: "Knitwear", catEs: "Punto", price: 540, stripe: "stripes", colorChip: "#e8e4dc", colors: ["Bone"], sizes: ["S","M","L"], material: "Cashmere", new: true, stock: { XS:0, S:5, M:7, L:5, XL:0 } },
  { id: "M-04", name: { en: "Rust Workshop Shirt", es: "Camisa de taller óxido" }, sku: "MO-WS-012", cat: "Shirts", catEs: "Camisas", price: 320, stripe: "stripes-rust", colorChip: "#c0432a", colors: ["Rust"], sizes: ["XS","S","M","L","XL"], material: "Cotton", stock: { XS:4, S:8, M:10, L:6, XL:3 } },
  { id: "M-05", name: { en: "Field Olive Parka", es: "Parka de campo oliva" }, sku: "MO-FP-002", cat: "Outerwear", catEs: "Abrigos", price: 980, stripe: "stripes-olive", colorChip: "#6e6f4f", colors: ["Olive"], sizes: ["M","L","XL"], material: "Cotton", stock: { XS:0, S:0, M:4, L:3, XL:2 } },
  { id: "M-06", name: { en: "Mason Linen Suit", es: "Traje de lino albañil" }, sku: "MO-MS-009", cat: "Tailoring", catEs: "Sastrería", price: 1480, stripe: "stripes-stone", colorChip: "#b8b5ad", colors: ["Stone","Bone"], sizes: ["S","M","L"], material: "Linen", stock: { XS:0, S:2, M:3, L:2, XL:0 } },
  { id: "M-07", name: { en: "Navy Reefer Jacket", es: "Chaqueta marinera marino" }, sku: "MO-RJ-003", cat: "Outerwear", catEs: "Abrigos", price: 860, stripe: "stripes-navy", colorChip: "#1f2b3e", colors: ["Navy"], sizes: ["S","M","L","XL"], material: "Wool", stock: { XS:0, S:5, M:6, L:4, XL:1 } },
  { id: "M-08", name: { en: "Studio Leather Derby", es: "Derby de cuero estudio" }, sku: "MO-LD-005", cat: "Footwear", catEs: "Calzado", price: 720, stripe: "stripes-dark", colorChip: "#0a0a0a", colors: ["Ink"], sizes: ["S","M","L"], material: "Leather", stock: { XS:0, S:0, M:0, L:0, XL:0 } },
  { id: "M-09", name: { en: "Quarry Knit Vest", es: "Chaleco punto cantera" }, sku: "MO-QV-011", cat: "Knitwear", catEs: "Punto", price: 380, stripe: "stripes-stone", colorChip: "#a8a59c", colors: ["Stone"], sizes: ["S","M","L","XL"], material: "Wool", stock: { XS:0, S:4, M:6, L:5, XL:3 } },
  { id: "M-10", name: { en: "Plaster Cotton Tee", es: "Camiseta algodón yeso" }, sku: "MO-PT-010", cat: "Shirts", catEs: "Camisas", price: 180, stripe: "stripes", colorChip: "#fafaf7", colors: ["Bone"], sizes: ["XS","S","M","L","XL"], material: "Cotton", stock: { XS:8, S:14, M:18, L:10, XL:6 } },
  { id: "M-11", name: { en: "Drafted Wide Trouser", es: "Pantalón ancho dibujado" }, sku: "MO-DW-013", cat: "Trousers", catEs: "Pantalones", price: 460, stripe: "stripes-dark", colorChip: "#0a0a0a", colors: ["Ink"], sizes: ["XS","S","M","L"], material: "Wool", new: true, stock: { XS:2, S:7, M:9, L:5, XL:0 } },
  { id: "M-12", name: { en: "Atelier Double-Breasted", es: "Doble botonadura atelier" }, sku: "MO-AD-006", cat: "Tailoring", catEs: "Sastrería", price: 1620, stripe: "stripes-navy", colorChip: "#1f2b3e", colors: ["Navy","Ink"], sizes: ["M","L","XL"], material: "Wool", stock: { XS:0, S:0, M:2, L:3, XL:1 } },
];

// ─────────────────────────────────────────────────────────────────
// MOCK DATA
// ─────────────────────────────────────────────────────────────────
const ORDERS = [
  { id: "MO-58210", date: "2026-05-12", items: 3, total: 1740, status: "intransit", piece: "Architect's Coat + 2" },
  { id: "MO-58041", date: "2026-04-28", items: 1, total: 540, status: "delivered", piece: "Bone Cashmere Crew" },
  { id: "MO-57902", date: "2026-04-14", items: 2, total: 740, status: "delivered", piece: "Workshop Shirt + 1" },
  { id: "MO-57755", date: "2026-03-30", items: 1, total: 420, status: "delivered", piece: "Pleated Trouser 04" },
  { id: "MO-57612", date: "2026-03-09", items: 4, total: 2180, status: "delivered", piece: "Mason Linen Suit + 3" },
  { id: "MO-57498", date: "2026-02-22", items: 1, total: 320, status: "returned", piece: "Rust Workshop Shirt" },
];

const LIVE_ORDERS = [
  { id: "MO-58319", who: "K. Almeida · Porto",     amount: 1240, t: "00:02" },
  { id: "MO-58318", who: "S. Watanabe · Kyoto",    amount:  540, t: "00:11" },
  { id: "MO-58317", who: "M. Ferrer · Barcelona",  amount:  860, t: "00:24" },
  { id: "MO-58316", who: "J. Lindqvist · Malmö",   amount:  320, t: "00:38" },
  { id: "MO-58315", who: "R. Okafor · Lagos",      amount: 1620, t: "01:02" },
  { id: "MO-58314", who: "E. Bauer · Zürich",      amount:  420, t: "01:14" },
];

const CLIENTS = [
  { name: "Kiyomi Tanaka",     contact: "k.tanaka@studio.jp",    loc: "Tokyo, JP",     status: "VIP",       value: 18420, last: "2026-05-12" },
  { name: "Mateo Ferrer",      contact: "mateo@ferrer.cat",      loc: "Barcelona, ES", status: "Active",    value:  6240, last: "2026-05-08" },
  { name: "Olivia Bauer",      contact: "olivia.b@arch.ch",      loc: "Zürich, CH",    status: "VIP",       value: 22180, last: "2026-05-04" },
  { name: "Rashid Okafor",     contact: "rashid@okafor.studio",  loc: "Lagos, NG",     status: "Active",    value:  4980, last: "2026-04-29" },
  { name: "Helena Quintana",   contact: "h.quintana@correo.mx",  loc: "CDMX, MX",      status: "Lapsed",    value:  1740, last: "2025-11-02" },
  { name: "Lukas Lindqvist",   contact: "lukas@malmo.se",        loc: "Malmö, SE",     status: "Active",    value:  3320, last: "2026-05-01" },
  { name: "Sara Watanabe",     contact: "sara@watanabe.kyoto",   loc: "Kyoto, JP",     status: "VIP",       value: 14620, last: "2026-05-14" },
  { name: "Diego Almeida",     contact: "d.almeida@porto.pt",    loc: "Porto, PT",     status: "Active",    value:  5180, last: "2026-05-10" },
];

const SUPPLIERS = [
  { name: "Casa de Lã, Bragança",       contact: "p.dias@casadela.pt",        loc: "Bragança, PT",   status: "Active",   cat: "Wool",     lead: "21 d" },
  { name: "Filature Roubaix",            contact: "claire@roubaix.fr",         loc: "Roubaix, FR",    status: "Active",   cat: "Cashmere", lead: "34 d" },
  { name: "Conceria Toscana",            contact: "info@concitos.it",          loc: "Pisa, IT",       status: "Active",   cat: "Leather",  lead: "28 d" },
  { name: "Linho do Alentejo",           contact: "vendas@linho.pt",           loc: "Évora, PT",      status: "Onboarding", cat: "Linen",  lead: "18 d" },
  { name: "Mühlbach Spinnerei",          contact: "info@muhl.de",              loc: "Augsburg, DE",   status: "Active",   cat: "Wool",     lead: "24 d" },
  { name: "Cotonificio Padano",          contact: "rete@cotpad.it",            loc: "Cremona, IT",    status: "Paused",   cat: "Cotton",   lead: "—"   },
];

const BANNERS = [
  { id: "B-01", title: { en: "SS/26 — On the floor", es: "PV/26 — En el suelo" }, body: { en: "Twenty-three pieces. One language. Live on the 14th.", es: "Veintitrés piezas. Un lenguaje. Activo el 14." }, cta: { en: "Enter", es: "Entrar" }, status: "live",      schedule: "2026-05-14" },
  { id: "B-02", title: { en: "The Field Parka", es: "La parka de campo" },        body: { en: "Re-issued in oiled cotton. Limited run of 80.", es: "Reedición en algodón engrasado. Tirada limitada de 80." }, cta: { en: "Reserve", es: "Reservar" }, status: "scheduled", schedule: "2026-06-02" },
  { id: "B-03", title: { en: "Atelier Hours", es: "Horario de atelier" },         body: { en: "Lisboa flagship now open Sundays.", es: "Tienda insignia de Lisboa abierta los domingos." }, cta: { en: "Visit", es: "Visitar" }, status: "draft",     schedule: "—" },
];

const PAGES = [
  { id: "P-01", title: { en: "About the atelier", es: "Sobre el atelier" },  status: "live",     updated: "2026-04-19" },
  { id: "P-02", title: { en: "Press & coverage", es: "Prensa" },              status: "live",     updated: "2026-03-02" },
  { id: "P-03", title: { en: "Sustainability", es: "Sostenibilidad" },        status: "draft",    updated: "2026-05-09" },
  { id: "P-04", title: { en: "Sizing & fit", es: "Tallas y corte" },          status: "live",     updated: "2026-02-14" },
];

const POLICIES = [
  { id: "L-01", title: { en: "Shipping & returns", es: "Envíos y devoluciones" }, status: "live",  updated: "2026-05-01" },
  { id: "L-02", title: { en: "Privacy", es: "Privacidad" },                       status: "live",  updated: "2026-04-22" },
  { id: "L-03", title: { en: "Terms of service", es: "Términos del servicio" },   status: "live",  updated: "2026-04-22" },
  { id: "L-04", title: { en: "Cookies", es: "Cookies" },                          status: "draft", updated: "2026-05-18" },
];

const NEWSLETTERS = [
  { id: "N-01", title: { en: "Issue No. 12 — On weight & drape", es: "Número 12 — Peso y caída" }, status: "live",      updated: "2026-05-04" },
  { id: "N-02", title: { en: "Issue No. 13 — The Field Parka", es: "Número 13 — La parka de campo" }, status: "scheduled", updated: "2026-06-02" },
];

const PAYMENT_METHODS = [
  { id: "card",  name: "Card payments",     desc: { en: "Visa, Mastercard, Amex via Stripe", es: "Visa, Mastercard, Amex vía Stripe" }, on: true  },
  { id: "paypal", name: "PayPal",           desc: { en: "Buy now, pay in 3", es: "Compra ahora, paga en 3" }, on: true  },
  { id: "klarna", name: "Klarna",           desc: { en: "Instalments at checkout", es: "Plazos en la caja" }, on: true  },
  { id: "apple",  name: "Apple Pay",        desc: { en: "One-tap on iOS & macOS", es: "Un toque en iOS y macOS" }, on: false },
  { id: "google", name: "Google Pay",       desc: { en: "One-tap on Android & web", es: "Un toque en Android y web" }, on: false },
  { id: "wire",   name: "Bank transfer",    desc: { en: "For orders over €2,000", es: "Para pedidos superiores a 2.000 €" }, on: true  },
];

// Tiny chart series (revenue last 30 days)
const REVENUE_SERIES = [12,18,15,22,28,24,31,29,34,30,38,42,45,40,48,52,49,58,62,55,64,71,68,74,79,82,88,84,92,98];
const TRAFFIC_SERIES = [4200, 5100, 4800, 6300, 5900, 7400, 7100];

// ─────────────────────────────────────────────────────────────────
// SOCIAL HUB
// ─────────────────────────────────────────────────────────────────
const SOCIAL_THREADS = [
  {
    id: "T-2114",
    channel: "ig",
    name: "Kiyomi Tanaka",
    handle: "@kiyomi.t",
    avatar: "stripes-dark",
    last: "Could you reserve the Architect's Coat in size M? I'll collect Friday in Lisboa.",
    time: "00:04",
    unread: 2,
    priority: true,
    status: "open",
    productRef: "M-01",
    messages: [
      { who: "them", at: "10:21", text: "Hola. I just saw the SS/26 drop on your story." },
      { who: "them", at: "10:22", text: "Could you reserve the Architect's Coat in size M? I'll collect Friday in Lisboa." },
      { who: "us",   at: "10:24", text: "Of course, Kiyomi. Reserved for you under your client number. Bring your ID at pickup." },
      { who: "them", at: "10:30", text: "Perfect. Any chance you also have the Quarry Vest in S?" },
    ],
  },
  {
    id: "T-2113",
    channel: "wa",
    name: "Mateo Ferrer",
    handle: "+34 612 994 008",
    avatar: "stripes-sand",
    last: "Tracking says delivered but I can't find the package — can you check?",
    time: "00:12",
    unread: 1,
    priority: true,
    status: "open",
    orderRef: "MO-58041",
    messages: [
      { who: "them", at: "11:02", text: "Tracking says delivered but I can't find the package — can you check?" },
      { who: "us",   at: "11:04", text: "Let me pull up MO-58041 right now. One moment." },
    ],
  },
  {
    id: "T-2112",
    channel: "ig",
    name: "Olivia Bauer",
    handle: "@olivia.bauer",
    avatar: "stripes-stone",
    last: "Reel saved 🤍",
    time: "00:38",
    unread: 0,
    status: "open",
    messages: [
      { who: "them", at: "Yesterday", text: "Reel saved 🤍" },
    ],
  },
  {
    id: "T-2111",
    channel: "wa",
    name: "Rashid Okafor",
    handle: "+234 803 412 7700",
    avatar: "stripes-rust",
    last: "Could you ship the Mason suit DDP to Lagos?",
    time: "01:14",
    unread: 0,
    status: "open",
    productRef: "M-06",
    messages: [
      { who: "them", at: "08:40", text: "Could you ship the Mason suit DDP to Lagos?" },
      { who: "us",   at: "09:02", text: "Yes — DDP all-in to LOS is €58. ETA 7-10 days. Want me to draft the quote?" },
      { who: "them", at: "09:12", text: "Please." },
    ],
  },
  {
    id: "T-2110",
    channel: "ig",
    name: "Lukas Lindqvist",
    handle: "@l.lindqvist",
    avatar: "stripes-navy",
    last: "Will the Pleated 04 restock in XL?",
    time: "02:48",
    unread: 0,
    status: "open",
    productRef: "M-02",
    messages: [
      { who: "them", at: "Mon", text: "Will the Pleated 04 restock in XL?" },
      { who: "us",   at: "Mon", text: "We're cutting another 12 pairs at the atelier — XL drops May 28. I'll ping you." },
    ],
  },
  {
    id: "T-2109",
    channel: "wa",
    name: "Sara Watanabe",
    handle: "+81 90 1284 6602",
    avatar: "stripes-olive",
    last: "Thank you, the parka arrived perfectly.",
    time: "Yesterday",
    unread: 0,
    status: "resolved",
    messages: [
      { who: "them", at: "Yesterday", text: "Thank you, the parka arrived perfectly." },
      { who: "us",   at: "Yesterday", text: "Wonderful. Wear it well, Sara." },
    ],
  },
  {
    id: "T-2108",
    channel: "ig",
    name: "Helena Quintana",
    handle: "@hquintana",
    avatar: "stripes-sand",
    last: "Is there a guide for the Architect's coat fit?",
    time: "2 days",
    unread: 0,
    status: "resolved",
    messages: [
      { who: "them", at: "Sun", text: "Is there a guide for the Architect's coat fit?" },
      { who: "us",   at: "Sun", text: "Sending the lookbook now — the M sits one size below a typical wool coat. DM if you want a video fitting." },
    ],
  },
  {
    id: "T-2107",
    channel: "wa",
    name: "Diego Almeida",
    handle: "+351 96 882 1004",
    avatar: "stripes",
    last: "Atelier hours on Sunday?",
    time: "3 days",
    unread: 0,
    status: "resolved",
    messages: [
      { who: "them", at: "Fri", text: "Atelier hours on Sunday?" },
      { who: "us",   at: "Fri", text: "11h–17h, by appointment. Want me to book you in?" },
    ],
  },
];

const SOCIAL_KPIS = {
  igReach30d:     128400,
  igEngagement:   9.4,
  waOpenRate:     86.2,
  waCTR:          14.1,
  scheduled:      9,
  unread:         3,
  followersIG:    42180,
  subscribersWA:  3840,
  attributed30d:  62420,
};

const SOCIAL_POSTS = [
  { id: "P-01", channel: "ig",  format: "Feed",      title: { en: "Architect's Coat — campaign still", es: "Abrigo del arquitecto — pieza de campaña" }, when: "May 22 · 09:00", status: "scheduled", reach: null,  stripe: "stripes-dark", product: "M-01" },
  { id: "P-02", channel: "ig",  format: "Story",     title: { en: "Behind the cutting room", es: "Detrás de la sala de corte" },                          when: "May 22 · 18:00", status: "scheduled", reach: null,  stripe: "stripes-stone", product: null },
  { id: "P-03", channel: "wa",  format: "Broadcast", title: { en: "VIP early access — Capsule 04", es: "Acceso VIP — Cápsula 04" },                       when: "May 23 · 11:00", status: "scheduled", reach: null,  stripe: "stripes-rust", product: null },
  { id: "P-04", channel: "ig",  format: "Reel",      title: { en: "Field Parka in oiled cotton", es: "Parka de campo en algodón engrasado" },              when: "May 24 · 12:00", status: "draft",     reach: null,  stripe: "stripes-olive", product: "M-05" },
  { id: "P-05", channel: "ig",  format: "Feed",      title: { en: "Bone cashmere · close-up", es: "Cachemir hueso · primer plano" },                       when: "May 20 · 09:00", status: "live",      reach: 18420, stripe: "stripes",       product: "M-03" },
  { id: "P-06", channel: "wa",  format: "Broadcast", title: { en: "Atelier Sundays — appointments", es: "Domingos de atelier — citas" },                   when: "May 18 · 10:00", status: "live",      reach:  3120, stripe: "stripes-sand",  product: null },
  { id: "P-07", channel: "ig",  format: "Story",     title: { en: "Capsule 04 unboxing", es: "Apertura de la Cápsula 04" },                                when: "May 16 · 17:00", status: "live",      reach: 22640, stripe: "stripes-navy",  product: null },
];

const SOCIAL_FUNNEL = [
  { l: "Impressions",       v: 412000, w: 100 },
  { l: "Profile visits",    v:  84200, w: 64 },
  { l: "Storefront clicks", v:  18420, w: 38 },
  { l: "Add to bag",        v:   4280, w: 22 },
  { l: "Orders",            v:   1284, w: 12 },
];

const SOCIAL_REACH_SERIES_IG = [3.2,3.8,4.4,4.1,5.0,5.6,5.2,6.0,6.4,7.0,7.6,7.2,8.0,8.4,9.0,8.8,9.6,10.2,10.0,11.0,11.6,12.0,12.4,12.8,13.0,13.6,14.2,14.0,15.0,15.6];
const SOCIAL_REACH_SERIES_WA = [0.6,0.8,0.7,0.9,1.0,1.1,1.0,1.2,1.3,1.4,1.3,1.5,1.6,1.7,1.6,1.8,1.9,2.0,1.9,2.1,2.2,2.3,2.4,2.3,2.5,2.6,2.7,2.6,2.8,2.9];

// Replied templates
const SOCIAL_TEMPLATES = [
  { id: "tmpl-1", l: { en: "Reservation confirmed", es: "Reserva confirmada" }, body: { en: "Reserved under your client number. Bring ID at pickup.", es: "Reservado bajo tu número de cliente. Trae el documento al retirar." } },
  { id: "tmpl-2", l: { en: "Restock notice",         es: "Aviso de reposición" }, body: { en: "We're cutting another batch — I'll ping you the moment it goes live.", es: "Estamos cortando un nuevo lote — te avisaré en cuanto entre." } },
  { id: "tmpl-3", l: { en: "DDP quote",              es: "Cotización DDP" },     body: { en: "DDP all-in to your address: €— total. ETA — days.", es: "DDP completo a tu dirección: €— total. Plazo — días." } },
  { id: "tmpl-4", l: { en: "Fitting invitation",     es: "Invitación a prueba" }, body: { en: "Want to book a fitting at the Lisboa atelier? Sundays 11h–17h.", es: "¿Reservamos una prueba en el atelier de Lisboa? Domingos 11h–17h." } },
];

// Sync coverage per channel — generated from PRODUCTS at runtime by component
// (we keep a small map here to mark exceptions)
const SOCIAL_SYNC_OVERRIDES = {
  "M-08": { ig: "stale", wa: "unlisted" }, // sold out + leather, paused on WA
  "M-12": { ig: "ok",    wa: "stale" },
  "M-06": { ig: "ok",    wa: "ok"   },
};

Object.assign(window, {
  T, PRODUCTS, ORDERS, LIVE_ORDERS, CLIENTS, SUPPLIERS,
  BANNERS, PAGES, POLICIES, NEWSLETTERS, PAYMENT_METHODS,
  REVENUE_SERIES, TRAFFIC_SERIES,
  SOCIAL_THREADS, SOCIAL_KPIS, SOCIAL_POSTS, SOCIAL_FUNNEL,
  SOCIAL_REACH_SERIES_IG, SOCIAL_REACH_SERIES_WA, SOCIAL_TEMPLATES, SOCIAL_SYNC_OVERRIDES,
});
